baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Collin Bolles'
theme = 'PaperMod'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 20
[[menu.main]]
  name = 'Project'
  url = '/projects'
  weight = 30

